### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

### ISSUE THREAD

**Issue by sandippshah** [MrMKN/Professor-bot#50]
Instance allocated in nomad
Instance is starting
Instance is unhealthy
Traceback (most recent call last):
  File "/workspace/bot.py", line 6, in <module>
    from database.ia_filterdb import Media
  File "/workspace/database/ia_filterdb.py", line 6, in <module>
    from pymongo.errors import DuplicateKeyError
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/__init__.py", line 116, in <module>
    from pymongo.mongo_client import MongoClient
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/mongo_client.py", line 46, in <module>
    from pymongo import (common,
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/uri_parser.py", line 32, in <module>
    from pymongo.srv_resolver import _HAVE_DNSPYTHON, _SrvResolver
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 18, in <module>
    from dns import resolver
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/query.py", line 67, in <module>
    _CoreNetworkBackend = httpcore.NetworkBackend
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'
Instance is unhealthy
Instance is unhealthy
Instance is unhealthy
Traceback (most recent call last):
  File "/workspace/bot.py", line 6, in <module>
    from database.ia_filterdb import Media
  File "/workspace/database/ia_filterdb.py", line 6, in <module>
    from pymongo.errors import DuplicateKeyError
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/__init__.py", line 116, in <module>
    from pymongo.mongo_client import MongoClient
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/mongo_client.py", line 46, in <module>
    from pymongo import (common,
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/uri_parser.py", line 32, in <module>
    from pymongo.srv_resolver import _HAVE_DNSPYTHON, _SrvResolver
  File "/app/.heroku/python/lib/python3.10/site-packages/pymongo/srv_resolver.py", line 18, in <module>
    from dns import resolver
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/resolver.py", line 30, in <module>
    import dns._ddr
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/asyncquery.py", line 38, in <module>
    from dns.query import (
  File "/app/.heroku/python/lib/python3.10/site-packages/dns/query.py", line 67, in <module>
    _CoreNetworkBackend = httpcore.NetworkBackend
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'
Instance terminated in nomad
Instance allocated in nomad
Instance is starting

**Comment by Mrblackgodd** [comment]
How to solve this??

**Comment by sandippshah** [comment]
dnspython==2.3.0

Add thiis in requirements.txt 
Solved problem 😁

**Comment by rev9dev** [comment]
You can run in WSL/ Linux based Cloud system.

**Comment by MrMKN** [comment]
Fixed
